### ISSUE TITLE
Question about admet dataset

### ISSUE THREAD

**Issue by mohammad-saber** [globus-labs/toxicity-prediction#1]
Hi, thank you very much for sharing your great work.

I have a question about [admet datasets](https://github.com/globus-labs/toxicity-prediction/tree/master/admet/datasets).

There are 4 CSV files including SMILES and toxicity labels. Are these labels obtained by experiment / clinical test or by prediction by [admetSAR](http://lmmd.ecust.edu.cn/admetsar2/)? 

Thank you very much fro your help.

**Comment by WardLT** [comment]
Those datasets CSV files are values from experiment tests. They are  the training data for the QSAR models and described more [here](https://academic.oup.com/bioinformatics/article/35/6/1067/5085368).
